services:
  grafana:
    platform: 'linux/amd64'
    build:
      args:
        grafana_version: latest
    ports:
      - 3000:3000/tcp
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    environment:
      LITMUS_EDGE_ACCESS_ACCOUNT_TOKEN: ${LITMUS_EDGE_ACCESS_ACCOUNT_TOKEN:-}
      LITMUS_EDGE_API_TOKEN: ${LITMUS_EDGE_API_TOKEN:-}
