services:
  grafana:
    platform: 'linux/amd64'
    build:
      args:
        grafana_version: latest
    ports:
      - 3000:3000/tcp
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    environment:
      EDGE_EXTERNAL: ${EDGE_EXTERNAL:-false}
      EDGE_DOCKER_GATEWAY_IP: ${EDGE_DOCKER_GATEWAY_IP:-10.30.50.1}
      EDGE_HOSTNAME: ${EDGE_HOSTNAME:-}
      EDGE_NATS_PROXY_PORT: ${EDGE_NATS_PROXY_PORT:-}
      EDGE_ACCESS_ACCOUNT_TOKEN: ${EDGE_ACCESS_ACCOUNT_TOKEN:-}
      EDGE_TOKEN: ${EDGE_TOKEN:-}
